### ISSUE TITLE
how to install on windows

### ISSUE THREAD

**Issue by molchanov1983** [expressif/pecl-event-libevent#12]
Hello
Can you help me please to make php_libevent.dll for php 7 (as i understand i need to make dll from source files located here http://libevent.org/ latest version 2.0.22 ).
Put php_libevent.dll into ext folder
And what should i do futher?

**Comment by ichiriac** [comment]
Hi @molchanov1983,

You don't need to build them, I've already done it.

You can download them from here :
https://github.com/expressif/win-dist#downloads
