### ISSUE TITLE
multi task request issue

### ISSUE THREAD

**Issue by molchanov1983** [expressif/pecl-event-libevent#13]
Hello Guys
Please help me with on equestion
For example i have ws connection oppened and send:
ws.send('{id:1,"method":"login, .... ); - takes 10 seconds 
ws.send('{id:2,method":"event_update_device_by_type_tree" ... '); -- takes 1 second

In this case i have such ordered response:
response {id: 1 ...},
response {id: 2 ...}

But i would have 
response {id: 2 ...},
response {id: 1 ...}
Can anybode say how to do it using GenericSelect class
Or it is not possible to use this class for solving this issue? 
Thanks

**Comment by ichiriac** [comment]
You maybe should open a ticket here : https://github.com/morozovsk/websocket, it seems you are not at the right place here.
