### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by ichiriac** [expressif/pecl-event-libevent#6]
@Joungkyun  : the thread was started here :
https://github.com/expressif/pecl-event-libevent/pull/5

Actually running php 7.0 branch (using exactly 7.0.2 version).

Builds pass if the debug mode is not enabled. WHen enabling the debug mode, this memory leak occurs :
https://travis-ci.org/expressif/pecl-event-libevent/jobs/105135041

Not sure, i've also tried to debug this and seems to be a bug in zend core.

@nikic or @laruence, could you help us to better understand this problem please ?

**Comment by nikic** [comment]
Does valgrind (e.g. run-tests.php -m) tell you anything useful? Also, it looks like you have an assertion failure in one of the tests...

**Comment by Joungkyun** [comment]
The leak of libevent002.phpt is occured follow conditions:
1. enable_debug option on
2. The callback fucntion of event_set is anonymous function
