### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by majuca** [expressif/pecl-event-libevent#9]
Hi,

I have sometimes a segmentation fault. The crash file indicate that the problem happens in the function event_free with the function call zend_list_close(Z_RES_P(event->rsrc_id)).

**Comment by majuca** [comment]
it seems that the patch in the issue #8 fixed the problem. I only patch the line with zend_list_close.

**Comment by ichiriac** [comment]
Hi @majuca,

I've reproduced the bug, it's a memory leak, I will work on it soon.

**Comment by ichiriac** [comment]
Hi @majuca, 

The bug is now fixed, no more memory leaks on event_free function (the proposed patch at https://github.com/expressif/pecl-event-libevent/issues/8 was just hiding errors)

**Comment by majuca** [comment]
Hi, seems to be ok, thank you for the fix
